# Project: expression
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o expression.o
LINKOBJ  = main.o expression.o
LIBS     = -L"D:/project-softwares/devc++/Dev-Cpp/MinGW64/lib" -L"D:/project-softwares/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/include" -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/include" -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/project-softwares/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = expression.exe
CXXFLAGS = $(CXXINCS) -std=c99 -g3
CFLAGS   = $(INCS) -std=c99 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

expression.o: expression.cpp
	$(CPP) -c expression.cpp -o expression.o $(CXXFLAGS)
